# Generated by Django 5.0.6 on 2024-06-15 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_plate_reg', models.CharField(max_length=50)),
                ('vehilce_type', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car')], max_length=50)),
                ('driverSlug', models.SlugField(unique=True)),
                ('DriverLicense', models.ImageField(upload_to='driver/license')),
                ('IsApproved', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now_add=True)),
                ('User_Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thedriverProfile', to='Accounts.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Driver',
            },
        ),
    ]
