# Generated by Django 5.0.7 on 2024-08-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driverSlug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_plate_reg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehilce_type',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car')], max_length=100),
        ),
    ]
